name: Full CI-CD Pipeline

on:
  push:
    branches:
      - master  # Change to 'main' if your default branch is main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Core Dependencies
        timeout-minutes: 10
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install DVC (Pinned)
        timeout-minutes: 10
        run: |
          pip install --upgrade pip
          pip uninstall -y dvc
          pip install --force-reinstall -r dvc-requirements.txt

      - name: Install Dev Dependencies
        timeout-minutes: 10
        run: |
          pip install -r requirements-dev.txt

      - name: Install Tools
        timeout-minutes: 5
        run: |
          pip install -r requirements-tools.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: DVC Pull Data & Models
        run: |
          dvc pull

      - name: Run Tests
        run: |
          pytest tests

      - name: Promote Best Model
        if: success()
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python scripts/promote_model_to_prod.py

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY_URI }}
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Zip Files for Deployment
        run: |
          zip -r deployment.zip appspec.yml deploy/scripts/

      - name: Upload ZIP to S3
        run: |
          aws s3 cp deployment.zip s3://deliverytimepredictiondeployment/deployment.zip

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name deliverytimeprediction \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name deliverytimepredictiondeploymentgroup \
            --s3-location bucket=deliverytimepredictiondeployment,key=deployment.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE \
            --region us-east-1
